# Core normalization settings
norm: 'zero2two'
mean: 259.3117656881453 
std: 362.1817760568698 

# Sampling configuration
line_search: True
fine_tune: False
skip_timestep: 949

# Data configuration
data:
  return_id: True

# Data normalization for datasets  
Data:
  mean_hr: 259.3117656881453 
  std_hr: 362.1817760568698 

# Conditioning method configuration
conditioning:
  method: 'ps'
  params:
    scale: 1.0

# Measurement operator configuration
measurement:
  operator:
    name: 'gaussian_blur'
    kernel_size: 11
    intensity: 1.0
  
  noise: 
    name: 'gaussian'
    sigma: 0.001
