# Core normalization settings
norm: 'zero2two'
mean: 259.3117656881453 
std: 362.1817760568698 

# Sampling configuration
<<<<<<< HEAD
line_search: False
fine_tune: False
skip_timestep: True
tau: 0.4
=======
line_search: True
fine_tune: False
skip_timestep: 949
>>>>>>> 4760da55a2d155e91f863a95444b62a8e5f9cfb4

# Data configuration
data:
  return_id: True

# Data normalization for datasets  
Data:
  mean_hr: 259.3117656881453 
  std_hr: 362.1817760568698 

# Conditioning method configuration
conditioning:
  method: 'ps'
  params:
    scale: 1.0

# Measurement operator configuration
measurement:
  operator:
    name: 'gaussian_blur'
    kernel_size: 11
    intensity: 1.0
  
  noise: 
    name: 'gaussian'
    sigma: 0.001
